/*
 *  Esta classe é uma janela (JDialog) que se abre quando um peão vai coroar
 * 
 * 
 */
package View;

import Model.Bispo;
import Model.Cavalo;
import Model.Peca;
import Model.Rainha;
import Model.Torre;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;


/**
 *
 * @author Ricardo Atakiama
 */
public class JDCoroar extends JDialog {

    private final Tabuleiro view;
    /**
     * Creates new form jdCoroar
     * @param parent
     * @param modal
     */
    public JDCoroar(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        view = (Tabuleiro) getParent();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_knight = new javax.swing.JLabel();
        jl_bishop = new javax.swing.JLabel();
        jl_rook = new javax.swing.JLabel();
        jl_queen = new javax.swing.JLabel();
        jb_knight = new javax.swing.JButton();
        jb_bishop = new javax.swing.JButton();
        jb_rook = new javax.swing.JButton();
        jb_queen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Escolha a peça");
        setAlwaysOnTop(true);

        jl_knight.setText("Cavalo");

        jl_bishop.setText("Bispo");

        jl_rook.setText("Torre");

        jl_queen.setText("Rainha");

        jb_knight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wKnight.png"))); // NOI18N
        jb_knight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_knightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jb_knightMouseExited(evt);
            }
        });
        jb_knight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_knightActionPerformed(evt);
            }
        });

        jb_bishop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wBishop.png"))); // NOI18N
        jb_bishop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_bishopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jb_bishopMouseExited(evt);
            }
        });
        jb_bishop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_bishopActionPerformed(evt);
            }
        });

        jb_rook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wRook.png"))); // NOI18N
        jb_rook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_rookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jb_rookMouseExited(evt);
            }
        });
        jb_rook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_rookActionPerformed(evt);
            }
        });

        jb_queen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wQueen.png"))); // NOI18N
        jb_queen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_queenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jb_queenMouseExited(evt);
            }
        });
        jb_queen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_queenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jb_knight)
                .addGap(26, 26, 26)
                .addComponent(jb_bishop)
                .addGap(27, 27, 27)
                .addComponent(jb_rook)
                .addGap(18, 18, 18)
                .addComponent(jb_queen)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jl_knight)
                .addGap(73, 73, 73)
                .addComponent(jl_bishop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_rook)
                .addGap(61, 61, 61)
                .addComponent(jl_queen)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_knight)
                    .addComponent(jb_bishop)
                    .addComponent(jb_rook)
                    .addComponent(jb_queen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_queen)
                        .addComponent(jl_rook))
                    .addComponent(jl_knight)
                    .addComponent(jl_bishop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_knightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_knightActionPerformed
        if(view.getController().getCoroada().getCor() == Peca.Cor.BRANCO)
            view.getModel().getPecasBrancas().add(new Cavalo(view.getModel(), Peca.Cor.BRANCO, (int)view.getController().getPos_coroar().getX(), (int)view.getController().getPos_coroar().getY()));
        else if(view.getController().getCoroada().getCor() == Peca.Cor.PRETO)
            view.getModel().getPecasPretas().add(new Cavalo(view.getModel(), Peca.Cor.PRETO, (int)view.getController().getPos_coroar().getX(), (int)view.getController().getPos_coroar().getY()));
        
        this.dispose();
    }//GEN-LAST:event_jb_knightActionPerformed

    private void jb_bishopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_bishopActionPerformed
        if(view.getController().getCoroada().getCor() == Peca.Cor.BRANCO)
            view.getModel().getPecasBrancas().add(new Bispo(view.getModel(), Peca.Cor.BRANCO, (int)view.getController().getPos_coroar().getX(), (int)view.getController().getPos_coroar().getY()));
        else if(view.getController().getCoroada().getCor() == Peca.Cor.PRETO)
            view.getModel().getPecasPretas().add(new Bispo(view.getModel(), Peca.Cor.PRETO, (int)view.getController().getPos_coroar().getX(), (int)view.getController().getPos_coroar().getY()));
        
        this.dispose();
    }//GEN-LAST:event_jb_bishopActionPerformed

    private void jb_rookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_rookActionPerformed
        if(view.getController().getCoroada().getCor() == Peca.Cor.BRANCO)
            view.getModel().getPecasBrancas().add(new Torre(view.getModel(), Peca.Cor.BRANCO, (int)view.getController().getPos_coroar().getX(), (int)view.getController().getPos_coroar().getY()));
        else if(view.getController().getCoroada().getCor() == Peca.Cor.PRETO)
            view.getModel().getPecasPretas().add(new Torre(view.getModel(), Peca.Cor.PRETO, (int)view.getController().getPos_coroar().getX(), (int)view.getController().getPos_coroar().getY()));
        
        this.dispose();
    }//GEN-LAST:event_jb_rookActionPerformed

    private void jb_queenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_queenActionPerformed
        if(view.getController().getCoroada().getCor() == Peca.Cor.BRANCO)
            view.getModel().getPecasBrancas().add(new Rainha(view.getModel(), Peca.Cor.BRANCO, (int)view.getController().getPos_coroar().getX(), (int)view.getController().getPos_coroar().getY()));
        else if(view.getController().getCoroada().getCor() == Peca.Cor.PRETO)
            view.getModel().getPecasPretas().add(new Rainha(view.getModel(), Peca.Cor.PRETO, (int)view.getController().getPos_coroar().getX(), (int)view.getController().getPos_coroar().getY()));
        
        this.dispose();
    }//GEN-LAST:event_jb_queenActionPerformed

    private void jb_knightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_knightMouseEntered
        getJl_knight().setForeground(Color.orange);
        getJl_knight().setBackground(Color.WHITE);
    }//GEN-LAST:event_jb_knightMouseEntered

    private void jb_knightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_knightMouseExited
        getJl_knight().setForeground(Color.BLACK);
        getJl_knight().setBackground(Color.BLACK);
    }//GEN-LAST:event_jb_knightMouseExited

    private void jb_bishopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_bishopMouseEntered
        getJl_bishop().setForeground(Color.orange);
        getJl_bishop().setBackground(Color.WHITE);
    }//GEN-LAST:event_jb_bishopMouseEntered

    private void jb_bishopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_bishopMouseExited
        getJl_bishop().setForeground(Color.BLACK);
        getJl_bishop().setBackground(Color.BLACK);
    }//GEN-LAST:event_jb_bishopMouseExited

    private void jb_rookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_rookMouseEntered
        getJl_rook().setForeground(Color.orange);
        getJl_rook().setBackground(Color.WHITE);
    }//GEN-LAST:event_jb_rookMouseEntered

    private void jb_rookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_rookMouseExited
        getJl_rook().setForeground(Color.BLACK);
        getJl_rook().setBackground(Color.BLACK);
    }//GEN-LAST:event_jb_rookMouseExited

    private void jb_queenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_queenMouseEntered
        getJl_queen().setForeground(Color.orange);
        getJl_queen().setBackground(Color.WHITE);
    }//GEN-LAST:event_jb_queenMouseEntered

    private void jb_queenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_queenMouseExited
        getJl_queen().setForeground(Color.BLACK);
        getJl_queen().setBackground(Color.BLACK);
    }//GEN-LAST:event_jb_queenMouseExited

    
    public JButton getJb_bishop() {
        return jb_bishop;
    }

    public JButton getJb_knight() {
        return jb_knight;
    }

    public JButton getJb_queen() {
        return jb_queen;
    }

    public JButton getJb_rook() {
        return jb_rook;
    }

    public JLabel getJl_bishop() {
        return jl_bishop;
    }

    public JLabel getJl_knight() {
        return jl_knight;
    }

    public JLabel getJl_queen() {
        return jl_queen;
    }

    public JLabel getJl_rook() {
        return jl_rook;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCoroar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCoroar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCoroar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCoroar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCoroar dialog = new JDCoroar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_bishop;
    private javax.swing.JButton jb_knight;
    private javax.swing.JButton jb_queen;
    private javax.swing.JButton jb_rook;
    private javax.swing.JLabel jl_bishop;
    private javax.swing.JLabel jl_knight;
    private javax.swing.JLabel jl_queen;
    private javax.swing.JLabel jl_rook;
    // End of variables declaration//GEN-END:variables

}
