/*
 * 
 * 
 */

/*
 * tabuleiro.java
 *
 * Created on 03/03/2011, 18:28:20
 */
package View;

import Controler.TabuleiroController;
import Model.AutoSave;
import Model.ModelTabuleiro;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Point;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo Atakiama
 */
public class Tabuleiro extends JFrame implements Observer {
  
    private ModelTabuleiro model;
    private TabuleiroController controller;
    private final Canvas canvas;
    private Point mouseCoord;

    
    public Tabuleiro(ModelTabuleiro model) {
        initComponents();

        canvas = new Canvas();
        mouseCoord = new Point();
        canvas.registerObserver(this);
        this.model = model;
        canvas.registerObserver(model);

        Dimension area = new Dimension(jPCanvas.getWidth(), jPCanvas.getHeight());
        canvas.setPreferredSize(area);//set dimensao do painel de desenho
        jPCanvas.setLayout(new GridLayout(1, 1));
        jPCanvas.add(canvas);
    }
    
    public ModelTabuleiro getModel() {
        return model;
    }

    public void setModel(ModelTabuleiro model) {
        this.model = model;
    }
    
    public TabuleiroController getController() {
        return controller;
    }

    public void setController(TabuleiroController controller) {
        this.controller = controller;
    }
    
    public Canvas getCanvas() {
        return canvas;
    }

    public Point getMouseCoord() {
        return mouseCoord;
    }

    public void setMouseCoord(Point mouseCoord) {
        this.mouseCoord = mouseCoord;
    }
  
//    public JLabel getClickLabel() {
//        return clickLabel;
//    }
//
//    public JLabel getCoordenadaLabel() {
//        return lbl_h_down;
//    }
//
//    public void setClickLabel(JLabel clickLabel) {
//        this.clickLabel = clickLabel;
//    }
//
//    public void setCoordenadaLabel(JLabel coordenadaLabel) {
//        this.coordenadaLabel = coordenadaLabel;
//    }
    
    public void addController(TabuleiroController controller){
        jPCanvas.addMouseListener(controller);
        jPCanvas.addMouseMotionListener(controller);
    }
  
    public void drawMouseQuadrante(Graphics2D g) {
        
        int width = canvas.getWidth()/8;
        int height = canvas.getHeight()/8;
        
        int qx = mouseCoord.x/width;
        int qy = mouseCoord.y/height;
        //System.out.println(qx + "   " + qy);
        
        int squareWidth = g.getClip().getBounds().width / 8;
        int squareHeight = g.getClip().getBounds().height / 8;
        
        squareWidth++; 
        squareHeight++; 

        //System.out.println(squareWidth + "   " + squareHeight);
        
        g.setColor(Color.blue);
        g.setStroke(new BasicStroke(2));
        g.drawRect(qx * squareWidth, qy * squareHeight, squareWidth, squareHeight);
        g.setColor(Color.BLACK);
        
    }   
    
    public void labelsAdjust(){ // qdo inverte as cores de lado, é preciso inverter a numeração
        
        Rectangle aux = lbl_1l.getBounds();
        lbl_1l.setBounds(lbl_8l.getBounds());
        lbl_8l.setBounds(aux);
        
        aux = lbl_2l.getBounds();
        lbl_2l.setBounds(lbl_7l.getBounds());
        lbl_7l.setBounds(aux);
        
        aux = lbl_3l.getBounds();
        lbl_3l.setBounds(lbl_6l.getBounds());
        lbl_6l.setBounds(aux);
        
        aux = lbl_4l.getBounds();
        lbl_4l.setBounds(lbl_5l.getBounds());
        lbl_5l.setBounds(aux);
        
        aux = lbl_1r.getBounds();
        lbl_1r.setBounds(lbl_8r.getBounds());
        lbl_8r.setBounds(aux);
        
        aux = lbl_2r.getBounds();
        lbl_2r.setBounds(lbl_7r.getBounds());
        lbl_7r.setBounds(aux);
        
        aux = lbl_3r.getBounds();
        lbl_3r.setBounds(lbl_6r.getBounds());
        lbl_6r.setBounds(aux);
        
        aux = lbl_4r.getBounds();
        lbl_4r.setBounds(lbl_5r.getBounds());
        lbl_5r.setBounds(aux);
    }
    
    
    
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCanvas = new javax.swing.JPanel();
        lbl_a_up = new javax.swing.JLabel();
        lbl_b_up = new javax.swing.JLabel();
        lbl_c_up = new javax.swing.JLabel();
        lbl_d_up = new javax.swing.JLabel();
        lbl_e_up = new javax.swing.JLabel();
        lbl_f_up = new javax.swing.JLabel();
        lbl_g_up = new javax.swing.JLabel();
        lbl_h_up = new javax.swing.JLabel();
        lbl_a_down = new javax.swing.JLabel();
        lbl_b_down = new javax.swing.JLabel();
        lbl_c_down = new javax.swing.JLabel();
        lbl_d_down = new javax.swing.JLabel();
        lbl_e_down = new javax.swing.JLabel();
        lbl_f_down = new javax.swing.JLabel();
        lbl_g_down = new javax.swing.JLabel();
        lbl_h_down = new javax.swing.JLabel();
        lbl_7r = new javax.swing.JLabel();
        lbl_6r = new javax.swing.JLabel();
        lbl_5r = new javax.swing.JLabel();
        lbl_4r = new javax.swing.JLabel();
        lbl_3r = new javax.swing.JLabel();
        lbl_2r = new javax.swing.JLabel();
        lbl_1r = new javax.swing.JLabel();
        lbl_8r = new javax.swing.JLabel();
        lbl_8l = new javax.swing.JLabel();
        lbl_7l = new javax.swing.JLabel();
        lbl_6l = new javax.swing.JLabel();
        lbl_5l = new javax.swing.JLabel();
        lbl_4l = new javax.swing.JLabel();
        lbl_3l = new javax.swing.JLabel();
        lbl_2l = new javax.swing.JLabel();
        lbl_1l = new javax.swing.JLabel();
        jl_background = new javax.swing.JLabel();
        jmb_barra = new javax.swing.JMenuBar();
        menu_arquivo = new javax.swing.JMenu();
        menu_novo = new javax.swing.JMenu();
        menuItem_novo_brancas = new javax.swing.JMenuItem();
        menuItem_novo_pretas = new javax.swing.JMenuItem();
        menuItem_salvar = new javax.swing.JMenuItem();
        menuItem_carregar = new javax.swing.JMenuItem();
        menuItem_voltar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItem_inverter = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItem_sobre = new javax.swing.JMenuItem();
        menuItem_sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCC0204 - RA Chess");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPCanvas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPCanvas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPCanvas.setMaximumSize(new java.awt.Dimension(400, 400));
        jPCanvas.setMinimumSize(new java.awt.Dimension(400, 400));
        jPCanvas.setOpaque(false);
        jPCanvas.setPreferredSize(new java.awt.Dimension(480, 480));
        jPCanvas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPCanvas, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 60, -1, -1));

        lbl_a_up.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_a_up.setForeground(new java.awt.Color(204, 204, 204));
        lbl_a_up.setText("A");
        getContentPane().add(lbl_a_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 28, -1, -1));

        lbl_b_up.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_b_up.setForeground(new java.awt.Color(204, 204, 204));
        lbl_b_up.setText("B");
        getContentPane().add(lbl_b_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 28, -1, -1));

        lbl_c_up.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_c_up.setForeground(new java.awt.Color(204, 204, 204));
        lbl_c_up.setText("C");
        getContentPane().add(lbl_c_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 28, -1, -1));

        lbl_d_up.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_d_up.setForeground(new java.awt.Color(204, 204, 204));
        lbl_d_up.setText("D");
        getContentPane().add(lbl_d_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 28, -1, -1));

        lbl_e_up.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_e_up.setForeground(new java.awt.Color(204, 204, 204));
        lbl_e_up.setText("E");
        getContentPane().add(lbl_e_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 28, -1, -1));

        lbl_f_up.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_f_up.setForeground(new java.awt.Color(204, 204, 204));
        lbl_f_up.setText("F");
        getContentPane().add(lbl_f_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 28, -1, -1));

        lbl_g_up.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_g_up.setForeground(new java.awt.Color(204, 204, 204));
        lbl_g_up.setText("G");
        getContentPane().add(lbl_g_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 28, -1, -1));

        lbl_h_up.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_h_up.setForeground(new java.awt.Color(204, 204, 204));
        lbl_h_up.setText("H");
        getContentPane().add(lbl_h_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 28, -1, -1));

        lbl_a_down.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_a_down.setForeground(new java.awt.Color(204, 204, 204));
        lbl_a_down.setText("A");
        getContentPane().add(lbl_a_down, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 558, -1, -1));

        lbl_b_down.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_b_down.setForeground(new java.awt.Color(204, 204, 204));
        lbl_b_down.setText("B");
        getContentPane().add(lbl_b_down, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 558, -1, -1));

        lbl_c_down.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_c_down.setForeground(new java.awt.Color(204, 204, 204));
        lbl_c_down.setText("C");
        getContentPane().add(lbl_c_down, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 558, -1, -1));

        lbl_d_down.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_d_down.setForeground(new java.awt.Color(204, 204, 204));
        lbl_d_down.setText("D");
        getContentPane().add(lbl_d_down, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 558, -1, -1));

        lbl_e_down.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_e_down.setForeground(new java.awt.Color(204, 204, 204));
        lbl_e_down.setText("E");
        getContentPane().add(lbl_e_down, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 558, -1, -1));

        lbl_f_down.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_f_down.setForeground(new java.awt.Color(204, 204, 204));
        lbl_f_down.setText("F");
        getContentPane().add(lbl_f_down, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 558, -1, -1));

        lbl_g_down.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_g_down.setForeground(new java.awt.Color(204, 204, 204));
        lbl_g_down.setText("G");
        getContentPane().add(lbl_g_down, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 558, -1, -1));

        lbl_h_down.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_h_down.setForeground(new java.awt.Color(204, 204, 204));
        lbl_h_down.setText("H");
        getContentPane().add(lbl_h_down, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 558, -1, -1));

        lbl_7r.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_7r.setForeground(new java.awt.Color(204, 204, 204));
        lbl_7r.setText("7");
        getContentPane().add(lbl_7r, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 147, -1, -1));

        lbl_6r.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_6r.setForeground(new java.awt.Color(204, 204, 204));
        lbl_6r.setText("6");
        getContentPane().add(lbl_6r, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 207, -1, -1));

        lbl_5r.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_5r.setForeground(new java.awt.Color(204, 204, 204));
        lbl_5r.setText("5");
        getContentPane().add(lbl_5r, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 267, -1, -1));

        lbl_4r.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_4r.setForeground(new java.awt.Color(204, 204, 204));
        lbl_4r.setText("4");
        getContentPane().add(lbl_4r, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 327, -1, -1));

        lbl_3r.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_3r.setForeground(new java.awt.Color(204, 204, 204));
        lbl_3r.setText("3");
        getContentPane().add(lbl_3r, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 387, -1, -1));

        lbl_2r.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_2r.setForeground(new java.awt.Color(204, 204, 204));
        lbl_2r.setText("2");
        getContentPane().add(lbl_2r, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 447, -1, -1));

        lbl_1r.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_1r.setForeground(new java.awt.Color(204, 204, 204));
        lbl_1r.setText("1");
        getContentPane().add(lbl_1r, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 507, -1, -1));

        lbl_8r.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_8r.setForeground(new java.awt.Color(204, 204, 204));
        lbl_8r.setText("8");
        getContentPane().add(lbl_8r, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 87, -1, -1));

        lbl_8l.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_8l.setForeground(new java.awt.Color(204, 204, 204));
        lbl_8l.setText("8");
        getContentPane().add(lbl_8l, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 87, -1, -1));

        lbl_7l.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_7l.setForeground(new java.awt.Color(204, 204, 204));
        lbl_7l.setText("7");
        getContentPane().add(lbl_7l, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 147, -1, -1));

        lbl_6l.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_6l.setForeground(new java.awt.Color(204, 204, 204));
        lbl_6l.setText("6");
        getContentPane().add(lbl_6l, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 207, -1, -1));

        lbl_5l.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_5l.setForeground(new java.awt.Color(204, 204, 204));
        lbl_5l.setText("5");
        getContentPane().add(lbl_5l, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 267, -1, -1));

        lbl_4l.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_4l.setForeground(new java.awt.Color(204, 204, 204));
        lbl_4l.setText("4");
        getContentPane().add(lbl_4l, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 327, -1, -1));

        lbl_3l.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_3l.setForeground(new java.awt.Color(204, 204, 204));
        lbl_3l.setText("3");
        getContentPane().add(lbl_3l, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 387, -1, -1));

        lbl_2l.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_2l.setForeground(new java.awt.Color(204, 204, 204));
        lbl_2l.setText("2");
        getContentPane().add(lbl_2l, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 447, -1, -1));

        lbl_1l.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_1l.setForeground(new java.awt.Color(204, 204, 204));
        lbl_1l.setText("1");
        getContentPane().add(lbl_1l, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 507, -1, -1));

        jl_background.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jl_background.setForeground(new java.awt.Color(204, 204, 204));
        jl_background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wood.jpg"))); // NOI18N
        jl_background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jl_background.setFocusable(false);
        jl_background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jl_background.setMaximumSize(new java.awt.Dimension(610, 660));
        jl_background.setMinimumSize(new java.awt.Dimension(610, 660));
        jl_background.setPreferredSize(new java.awt.Dimension(610, 660));
        getContentPane().add(jl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        menu_arquivo.setText("Arquivo");
        menu_arquivo.setContentAreaFilled(false);
        menu_arquivo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                menu_arquivoMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });

        menu_novo.setText("Novo jogo");
        menu_novo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                menu_novoMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });

        menuItem_novo_brancas.setText("Brancas");
        menuItem_novo_brancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_novo_brancasActionPerformed(evt);
            }
        });
        menu_novo.add(menuItem_novo_brancas);

        menuItem_novo_pretas.setText("Pretas");
        menuItem_novo_pretas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_novo_pretasActionPerformed(evt);
            }
        });
        menu_novo.add(menuItem_novo_pretas);

        menu_arquivo.add(menu_novo);

        menuItem_salvar.setText("Salvar jogo");
        menuItem_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_salvarActionPerformed(evt);
            }
        });
        menu_arquivo.add(menuItem_salvar);

        menuItem_carregar.setText("Carregar jogo");
        menuItem_carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_carregarActionPerformed(evt);
            }
        });
        menu_arquivo.add(menuItem_carregar);

        menuItem_voltar.setText("Voltar lance");
        menuItem_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_voltarActionPerformed(evt);
            }
        });
        menu_arquivo.add(menuItem_voltar);
        menu_arquivo.add(jSeparator1);

        menuItem_inverter.setText("Inverter tabuleiro");
        menuItem_inverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_inverterActionPerformed(evt);
            }
        });
        menu_arquivo.add(menuItem_inverter);
        menu_arquivo.add(jSeparator2);

        menuItem_sobre.setText("Sobre");
        menuItem_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_sobreActionPerformed(evt);
            }
        });
        menu_arquivo.add(menuItem_sobre);

        menuItem_sair.setText("Sair");
        menuItem_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_sairActionPerformed(evt);
            }
        });
        menu_arquivo.add(menuItem_sair);

        jmb_barra.add(menu_arquivo);

        setJMenuBar(jmb_barra);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_voltarActionPerformed
        System.out.println("voltando lance");
        
        ArrayList<ModelTabuleiro> lista = AutoSave.load("lastMove");
        
        ModelTabuleiro novoModel = lista.get(lista.size()-1);
        
        model.reset();
        
        setModel(novoModel);
        canvas.getObservers().remove(canvas.getObservers().size()-1); // remove o ultimo model
        canvas.registerObserver(novoModel);
        controller.addModel(novoModel);
        
        repaint();
    }//GEN-LAST:event_menuItem_voltarActionPerformed

    private void menuItem_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_sobreActionPerformed
        JOptionPane.showMessageDialog(null, "Jogo desenvolvido por Ricardo Atakiama", "Informações", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItem_sobreActionPerformed

    private void menuItem_novo_brancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_novo_brancasActionPerformed
        model.reset();
        
        if(!model.isWhiteBotton())labelsAdjust();        
        
        model.init();
        
        repaint();
        
        if(!getController().getUltimoLance().isEmpty()) getController().getUltimoLance().remove(0);
        getController().getUltimoLance().add(model);
        AutoSave.save(getController().getUltimoLance(), "lastMove");
    
    }//GEN-LAST:event_menuItem_novo_brancasActionPerformed

    private void menuItem_novo_pretasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_novo_pretasActionPerformed
        model.reset();
        
        if(model.isWhiteBotton())labelsAdjust();
        
        model.initBlack();
        
        repaint();
        
        if(!getController().getUltimoLance().isEmpty()) getController().getUltimoLance().remove(0);
        getController().getUltimoLance().add(model);
        AutoSave.save(getController().getUltimoLance(), "lastMove");
    }//GEN-LAST:event_menuItem_novo_pretasActionPerformed

    private void menuItem_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItem_sairActionPerformed

    private void menuItem_carregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_carregarActionPerformed
        System.out.println("carregando");
        
        ArrayList<ModelTabuleiro> lista = AutoSave.load("save");
        
        ModelTabuleiro novoModel = lista.get(lista.size()-1);
        
        model.reset();
        
        setModel(novoModel);
        canvas.getObservers().remove(canvas.getObservers().size()-1); // remove o ultimo model
        canvas.registerObserver(novoModel);
        controller.addModel(novoModel);
        
        repaint();
    }//GEN-LAST:event_menuItem_carregarActionPerformed

    private void menuItem_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_salvarActionPerformed
        ArrayList<ModelTabuleiro> save = new ArrayList<ModelTabuleiro>();

        save.add(getModel());
        AutoSave.save(save, "save");
        System.out.println("salvando");
    }//GEN-LAST:event_menuItem_salvarActionPerformed

    private void menu_arquivoMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu_arquivoMenuDeselected
        repaint();
    }//GEN-LAST:event_menu_arquivoMenuDeselected

    private void menu_novoMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu_novoMenuDeselected
        repaint();
    }//GEN-LAST:event_menu_novoMenuDeselected

    private void menuItem_inverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_inverterActionPerformed
        if(model.isWhiteBotton())model.setWhiteBotton(false);
        else if(!model.isWhiteBotton())model.setWhiteBotton(true);
        
        for(int i=0; i<model.getPecasBrancas().size(); i++){
            model.getPecasBrancas().get(i).setQuadrante(7 - (int)model.getPecasBrancas().get(i).getQuadrante().getX(),
                                                        7 - (int)model.getPecasBrancas().get(i).getQuadrante().getY());
        }
        for(int i=0; i<model.getPecasPretas().size(); i++){
            model.getPecasPretas().get(i).setQuadrante(7 - (int)model.getPecasPretas().get(i).getQuadrante().getX(),
                                                        7 - (int)model.getPecasPretas().get(i).getQuadrante().getY());
        }
        
        labelsAdjust();
    }//GEN-LAST:event_menuItem_inverterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPCanvas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel jl_background;
    private javax.swing.JMenuBar jmb_barra;
    private javax.swing.JLabel lbl_1l;
    private javax.swing.JLabel lbl_1r;
    private javax.swing.JLabel lbl_2l;
    private javax.swing.JLabel lbl_2r;
    private javax.swing.JLabel lbl_3l;
    private javax.swing.JLabel lbl_3r;
    private javax.swing.JLabel lbl_4l;
    private javax.swing.JLabel lbl_4r;
    private javax.swing.JLabel lbl_5l;
    private javax.swing.JLabel lbl_5r;
    private javax.swing.JLabel lbl_6l;
    private javax.swing.JLabel lbl_6r;
    private javax.swing.JLabel lbl_7l;
    private javax.swing.JLabel lbl_7r;
    private javax.swing.JLabel lbl_8l;
    private javax.swing.JLabel lbl_8r;
    private javax.swing.JLabel lbl_a_down;
    private javax.swing.JLabel lbl_a_up;
    private javax.swing.JLabel lbl_b_down;
    private javax.swing.JLabel lbl_b_up;
    private javax.swing.JLabel lbl_c_down;
    private javax.swing.JLabel lbl_c_up;
    private javax.swing.JLabel lbl_d_down;
    private javax.swing.JLabel lbl_d_up;
    private javax.swing.JLabel lbl_e_down;
    private javax.swing.JLabel lbl_e_up;
    private javax.swing.JLabel lbl_f_down;
    private javax.swing.JLabel lbl_f_up;
    private javax.swing.JLabel lbl_g_down;
    private javax.swing.JLabel lbl_g_up;
    private javax.swing.JLabel lbl_h_down;
    private javax.swing.JLabel lbl_h_up;
    private javax.swing.JMenuItem menuItem_carregar;
    private javax.swing.JMenuItem menuItem_inverter;
    private javax.swing.JMenuItem menuItem_novo_brancas;
    private javax.swing.JMenuItem menuItem_novo_pretas;
    private javax.swing.JMenuItem menuItem_sair;
    private javax.swing.JMenuItem menuItem_salvar;
    private javax.swing.JMenuItem menuItem_sobre;
    private javax.swing.JMenuItem menuItem_voltar;
    private javax.swing.JMenu menu_arquivo;
    private javax.swing.JMenu menu_novo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        drawMouseQuadrante((Graphics2D) arg);
    }
}
